### PR TITLE
Added support for decorating apps built using Flask-RESTful Resources

### PR DESCRIPTION
**Pull request by TheMourningDawn**
Fixes issue: https://github.com/di/flask-accept/issues/5

### CODE REVIEW

**Comment by di** [comment]
Thanks! Looks good to me, there is a small issue with the `README.rst`, if you `pip install readme_renderer` and then `setup.py check -r s` it will show you the problem:

```
$ python setup.py check -r -s
running check
warning: Check: :181: (WARNING/2) Title underline too short.
warning: Check:
warning: Check: Works with Flask-RESTful Resources
warning: Check: ^^^^^^^^^^^^^^^^^^^
warning: Check: Invalid markup which will not be rendered on PyPI.
error: Please correct your package.
```

(sorry there isn't CI to catch this!)

**Comment by TheMourningDawn** [comment]
Great! I've fixed the issue with the readme_renderer check failing. Should be good now!

**Comment by di** [comment]
Thanks!

**Comment by di** [comment]
This has been released on PyPI: https://pypi.org/project/flask_accept/

**Pull request merged**
